<html>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:31 GMT -->
<head>
      <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
   <title>Chapter 12. Exceptions</title><meta name="generator" content="DocBook XSL Stylesheets V1.50.0"><meta name="keywords" content="python, biology, bioinformatics, programming, computational biology"><link rel="home" href="index-2.html" title="Introduction to Programming using Python"><link rel="up" href="index-2.html" title="Introduction to Programming using Python"><link rel="previous" href="ch11s07.html" title="11.7. List comprehensions"><link rel="next" href="ch12s02.html" title="12.2. Python built-in exceptions"></head><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Chapter 12. Exceptions</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="ch11s07.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><th width="60%" align="center">&nbsp;</th><td width="20%" align="right">&nbsp;<a accesskey="n" href="ch12s02.html"><img src="images/next.png" alt="Next"></a></td></tr></table><hr></div><div class="chapter"><div class="titlepage"><div><h2 class="title"><a name="chapter_exceptions"></a>Chapter 12. Exceptions</h2></div></div><div class="toc"><p><b>Table of Contents</b></p><dl><dt>12.1. <a href="ch12.html#d0e4887">General Mechanism</a></dt><dt>12.2. <a href="ch12s02.html">Python built-in exceptions</a></dt><dt>12.3. <a href="ch12s03.html">Raising exceptions</a></dt><dt>12.4. <a href="ch12s04.html">Defining exceptions</a></dt></dl></div><div class="sect1"><div class="titlepage"><div><h2 class="title" style="clear: both"><a name="d0e4887"></a>12.1. General Mechanism</h2></div></div><p>
	Exceptions are a mechanism to handle errors during the execution
	of a program. An exception is <span class="emphasis"><em>raised</em></span>
	whenever an error occurs:

	</p><div class="example"><a name="sa_exc_file"></a><p class="title"><b>Example 12.1. Filename error</b></p><p>
	    <pre class="programlisting">
&gt;&gt;&gt; f = open('my_fil')
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in ?
IOError: [Errno 2] No such file or directory: 'my_fil'
            </pre>

	    An exception can be
	    <span class="emphasis"><em>caught</em></span> by the code where the error occurred:

	    <pre class="programlisting">
	    try:
	       f = open('my_fil')
	    except IOError, e:
	       print e
	    </pre>
	    Variable <tt>e</tt> contains the cause of the error:
	    <pre class="programlisting">
	    [Errno 2] No such file or directory: 'my_fil'
	    </pre>
	  </p></div><p>

	You could use this exception mechanism to prompt the user  in order 
	to get a proper filename. 

	</p><div class="example"><a name="exa_try_file"></a><p class="title"><b>Example 12.2. Give the user a chance to enter a proper
	  filename</b></p><p>
	    The following program makes a
	    first try with the name of a file provided on the Unix
	    command line. In case of problem, the user is prompted for
	    a valid file name, with the possibility to have a maximum
	    of 3 tries.
	    <pre class="programlisting">
import sys

filename = sys.argv[1]
max_tries = 3
tries = 0

while tries &lt; max_tries:
    try:
        f = open(filename)
        break
    except IOError, e:
        print e
        tries = tries + 1
        if tries &lt; max_tries:
            filename = raw_input("Enter a filename (%d tries left): " % (max_tries - tries))


if tries == max_tries:
    print "The program needs an existing filename, sorry."
    sys.exit(-1)

print "Execution of the program proceeds..."
for l in f:
    print l,

f.close()
            </pre>

	  </p></div><p>

      </p><p>
	If you need to protect your code from more than one error, you
	can specify several exceptions:

	    <pre class="programlisting">
	    try:
	       y = x / n
	    except ZeroDivisionError, e:
	       print "n is 0", e
	    except OverflowError, e:
	       print "%4.2f / %4.2f raises an overflow!" % (x,n), e
	    </pre>

      </p></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="ch11s07.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><td width="20%" align="center"><a accesskey="u" href="index-2.html"><img src="images/up.png" alt="Up"></a></td><td width="40%" align="right">&nbsp;<a accesskey="n" href="ch12s02.html"><img src="images/next.png" alt="Next"></a></td></tr><tr><td width="40%" align="left" valign="top">11.7. List comprehensions&nbsp;</td><td width="20%" align="center"><a accesskey="h" href="index-2.html"><img src="images/home.png" alt="Home"></a></td><td width="40%" align="right" valign="top">&nbsp;12.2. Python built-in exceptions</td></tr></table></div></body>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:31 GMT -->
</html>